### ISSUE TITLE
Release crate?

### ISSUE THREAD

**Issue by sandreae** [smmoosavi/dynamic-graphql#4]
Thanks for this handy library @smmoosavi, i was wondering if you had plans to make a release? We'd like to use it in https://github.com/p2panda/aquadoggo, but for us it would need to be released....

**Comment by smmoosavi** [comment]
It already exists. https://crates.io/crates/dynamic-graphql

**Comment by sandreae** [comment]
Oh great!! Why did I think that didn't exist...?

Thanks so much :+1:
